server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/fox_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  redis:
      host: 192.168.221.133
      port: 6379
      timeout: 10000
      database: 0
      lettuce:
       pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
user:
  dir: F:\Workspaces5\fox-shop-parent
  jwtset:
    signature: "wkxkx"
    exptime: 999999999
    alg: "HS256"
    type: "JWT"
